name: epub_ssr
description: Epub Parser for Dart. Suitable for use on the Server, the Web, or in Flutter
version: 2.1.0
homepage: https://github.com/WuXuBaiYang/epub-ssr

environment:
  sdk: ^3.8.0

dependencies:
  archive: ^4.0.7
  xml: ^6.6.1
  image: ^4.5.4
  convert: ^3.1.2

dev_dependencies:
